import { test } from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";

import { runZeroPr } from "./zero-pr-extension.ts";

function fake(responses: Array<{ code?: number; out?: string; err?: string; error?: Error }>) { const calls: string[][] = []; const bodies: string[] = []; const spawn = (_: string, args: string[]) => { calls.push(args); const bodyFile = args[args.indexOf("--body-file") + 1]; if (args.includes("--body-file") && bodyFile) bodies.push(readFileSync(bodyFile, "utf8")); const r = responses.shift() ?? { out: "" }; if (r.error) throw r.error; const child = new EventEmitter() as any; child.stdout = new Readable({ read() {} }); child.stderr = new Readable({ read() {} }); queueMicrotask(() => { if (r.out) child.stdout.emit("data", r.out); if (r.err) child.stderr.emit("data", r.err); child.emit("close", r.code ?? 0); }); return child; }; return { spawn, calls, bodies }; }
function ctx() { const notes: any[] = []; return { notes, ctx: { ui: { notify: (m: string, t?: string) => notes.push([m, t]) } } }; }
function fixture(fn: (dir: string) => Promise<void> | void) { return async () => { const dir = mkdtempSync(join(tmpdir(), "zero-pr-")); const old = process.cwd(); const oldEnv = process.env.ZERO_RUNS_PATH; process.chdir(dir); process.env.ZERO_RUNS_PATH = join(dir, "runs.jsonl"); try { mkdirSync(join(".sdd", "alpha"), { recursive: true }); writeFileSync(join(".sdd", "alpha", "proposal.md"), "# P\n\nDo thing."); writeFileSync(join(".sdd", "alpha", "spec.md"), "Acceptance criteria:\n- ok"); writeFileSync(join(".sdd", "alpha", "tasks.md"), "## [ ] T1\n- files:\n  - `x.ts`"); await fn(dir); } finally { process.chdir(old); if (oldEnv === undefined) delete process.env.ZERO_RUNS_PATH; else process.env.ZERO_RUNS_PATH = oldEnv; rmSync(dir, { recursive: true, force: true }); } }; }
function passRun(dir: string) { writeFileSync(join(dir, "runs.jsonl"), JSON.stringify({ v: 2, ts: "2026-01-01T00:00:00Z", feature: "alpha", phases: { explore: { model: "m" }, plan: { model: "m" }, build: { model: "m" }, veredicto: { model: "m" } }, verdict: "pasa", rounds: 1, verdicts: ["pasa"], reasoning: "npm test" }) + "\n"); }

test("/zero-pr reports ambiguous slug", fixture(async () => { mkdirSync(join(".sdd", "beta")); const c = ctx(); await runZeroPr("", c.ctx as any, fake([]).spawn as any); assert.match(c.notes[0][0], /no hay un único/); }));
test("/zero-pr blocks non-pasa verdict", fixture(async (dir) => { writeFileSync(join(dir, "runs.jsonl"), ""); const c = ctx(); await runZeroPr("alpha", c.ctx as any, fake([]).spawn as any); assert.match(c.notes[0][0], /no tiene veredicto pasa/); }));
test("/zero-pr reports missing gh", fixture(async (dir) => { passRun(dir); const c = ctx(); await runZeroPr("alpha", c.ctx as any, fake([{ error: new Error("ENOENT") }]).spawn as any); assert.equal(c.notes[0][1], "error"); }));
test("/zero-pr reports gh create failure and cleans tmp body", fixture(async (dir) => { passRun(dir); const f = fake([{ out: "gh version 2.0.0" }, { out: "[]" }, { code: 2, err: "bad" }]); const c = ctx(); await runZeroPr("alpha", c.ctx as any, f.spawn as any); assert.match(c.notes[0][0], /falló/); const bodyFile = f.calls.at(-1)?.[5] ?? ""; assert.equal(existsSync(bodyFile), false); }));
test("/zero-pr creates PR with body-file, writes links, reports skipped labels, and includes closes only with issue link", fixture(async (dir) => { passRun(dir); writeFileSync(join(".sdd", "alpha", "links.json"), JSON.stringify({ issueNumber: 9 })); const f = fake([{ out: "gh version 2.0.0" }, { out: '[{"name":"other"}]' }, { out: "https://github.com/o/r/pull/4" }]); const c = ctx(); await runZeroPr("alpha", c.ctx as any, f.spawn as any); const links = JSON.parse(readFileSync(join(".sdd", "alpha", "links.json"), "utf8")); assert.equal(links.prNumber, 4); const call = f.calls.at(-1) ?? []; assert.equal(call.includes("--body-file"), true); assert.equal(call.includes("--json"), false); assert.match(f.bodies[0], /Closes #9/); assert.match(c.notes[0][0], /skipié labels que no existen en este repo: type:feature, status:approved/); assert.equal(existsSync(call[5]), false); }));
